### ISSUE TITLE
Issues running util/runconfig_gcc_libint_openmp

### ISSUE THREAD

**Issue by nomicflux** [liresearchgroup/chronusq_public#1]
I've been having a few issues installing CQ using the runconfig file.  

First, it keeps telling me that the symlink build_gcc_libint_openmp/chronusQ already exists.  I'll delete it and it will go on with the next step of the installation.  This happened a couple times.

Second, there was an issue installing aointegrals_builders.cpp:
![error installing cq](https://cloud.githubusercontent.com/assets/13767188/10989535/05924572-840e-11e5-8edf-58430012c370.png)

Any ideas on what might be missing?  Thanks!

**Comment by wavefunction91** [comment]
Thank you for expressing interest in CQ. The runconfig files were a quick solution for configuration on the primary development machine of the Li Research Group. They haven't actively been used in some time, and they shouldn't have been included in the final repository. 

As for addressing the issues:

1) The configure scripts that are (for now) included automatically generate a symlink (even if the compilation fails). This means that if you continue to run the script multiple times, it will continue to attempt to create the symlink (hence the problem). Once the build directory is created and cmake has been executed (with the proper parameters for your system, of course), there is no need to re-run the configure script. This symlink is also not important now, regardless, as we've moved to a python API (chronusq.py is created), and the executable that the symlink points to (while functional) will not work with the current input file and most of the existing functionality is not accessible. I'll go through and remove these outdated files and make targets.

2) The error you are getting in aointegrals_builders.cpp is a problem with Eigen3 it sounds like. CQ depends (for the time being) on the Eigen3 library for basic linear algebra tasks. It looks like you are not linking to Eigen3 properly. The irony of this problem is that the section of code that is throwing an error is not currently accessible and is very experimental (Density Fitting is not currently, fully implemented throughout the code). To address this, and all other problems with properly installing and linking CQ to its dependencies, please refer to the User Manual in the doc directory. This holds for proper invocation of cmake for a proper configure as well.

I'll leave this issue open for now until we figure out how to properly install CQ on your system.

**Comment by nomicflux** [comment]
Ok.  For reference, this build is for a relatively new and up-to-date Gentoo VM.  Most of the libraries have been easily accessible, though I had to do a little work for BTAS.  Once we can figure out how to get everything compiling, I'll submit a pull request with additional documentation and such.

**Comment by wavefunction91** [comment]
Yes, as BTAS is not a usual dependency (I believe only a small group of researchers use it), it is not accessible through package managers (as far as I know). We look forward to getting your input regarding documentation.

**Comment by nomicflux** [comment]
Ok, I have successfully built CQ on my computer, and submitted a pull request with some of the fixes.  I'll open up some more specific issues regarded the problems I had.

**Comment by wavefunction91** [comment]
It should be noted that the actual error that opened this issue was due to linking to the wrong version of Eigen3.
