### ISSUE TITLE
Linking to correct Python libraries

### ISSUE THREAD

**Issue by nomicflux** [liresearchgroup/chronusq_public#4]
Boost is set to be compiled with Python2.7; however, at the end of the entire process when creating the chronusQ executable, make tried to link the project to Python3.4.

I solved this by forcing the compiler to link to the correct version of Python; this can be set manually by the user by changing the PYTHON_INCLUDE_DIR and PYTHON_LIBRARY options in the CMakeCache.txt file, but it would be nicer to have cmake find the correct version automatically.  

I tried setting the above options in the CMakeLists.txt file, but they were overwritten.  What seems to be needed is a way to tell cmake to not look for a version of Python beyond Python2.7, but all I've found so far is ways to link to specific directories and library files to enforce this, which of course is system-dependent.

**Comment by wavefunction91** [comment]
These parameters can be set at configure time (see comment section for #3 ). What you can try (as I don't have any machines where this is a problem) is to change the following lines in CMakeLists.txt

find_package(PythonLibs REQUIRED) -> find_package(PythonLibs 2.7 REQUIRED) 
find_package(PythonInterp REQUIRED) -> find_package(PythonInterp 2.7 REQUIRED) 

Checking out some forum threads, this should tell cmake to only find python2 libs with v2.7+ (i.e. not python3). I think that the problem that is caused by this is due to python3, not a different version of python2.

Alternatively, we can compile Boost.Python with python3, but I'm not sure that the current API will work with python3 (I can't see why it wouldn't, but that would take some development/debugging time). I think that the best current solution is to tell CMake to look for Python2.
